apiVersion: apps/v1
kind: Deployment
metadata:
  name: SampleDockerApp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: SampleDockerApp
  template:
    metadata:
      labels:
        app: SampleDockerApp
    spec:
      containers:
      - name: SampleDockerApp
        image: samplecontainer11.azurecr.io/kararchana/sampleappforhelm:#{Build.BuildId}#
        ports:
        - containerPort: 80
        env:
          - name: PODNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
      imagePullSecrets:
      - name: demoaks
---
apiVersion: v1
kind: Service
metadata:
  name: SampleDockerApp
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: SampleDockerApp
    apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: SampleDockerApp
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: SampleDockerApp.8d00e524230642a99b15.westus.aksapp.io                                          
    http:
      paths:
      - backend:
          serviceName: SampleDockerApp
          servicePort: 80
        path: /
---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: SampleDockerApp
  namespace: default
spec:
  minReplicas: 5
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: SampleDockerApp-deployment
  targetCPUUtilizationPercentage: 10
