apiVersion: apps/v1
kind: Deployment
metadata:
  name: SampleDockerApp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: SampleDockerApp
  template:
    metadata:
      labels:
        app: SampleDockerApp
    spec:
      containers:
      - name: SampleDockerApp
        image: sampledockerapp.azurecr.io/reddivaripriyanka/sampleappforhelm:#{Build.BuildId}#
        ports:
        - containerPort: 80
        env:
          - name: PODNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
      imagePullSecrets:
      - name: dockerapp
---
apiVersion: v1
kind: Service
metadata:
  name: SampleDockerApp
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: SampleDockerApp